# Generated by Django 5.0 on 2024-06-02 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentpotential',
            name='title',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacansy',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
