# Generated by Django 5.0 on 2024-06-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_investmentpotential_short_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycategory',
            name='text_footer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='text_header',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
