from .static import *
from .util_views import *
from .home_view import *
from .translations import *
from .main import *
from .activities import *
from .education_views import *
from .regulatory_documents_views import *
from .opensource_documents_views import *
from .services import *