# Generated by Django 5.0 on 2024-06-10 10:02

import custom.models
import django.db.models.deletion
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.JSONField(validators=[custom.models.json_field_validate])),
                ('answer', models.JSONField(validators=[custom.models.json_field_validate])),
            ],
        ),
        migrations.CreateModel(
            name='InteractiveServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(validators=[custom.models.json_field_validate])),
                ('url', models.JSONField(validators=[custom.models.json_field_validate])),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(validators=[custom.models.json_field_validate])),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.JSONField(validators=[custom.models.json_field_validate])),
            ],
        ),
        migrations.CreateModel(
            name='UserOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('opinion', 'Fikr va takliflar'), ('appeal', 'Jismoniy va yuridik shaxslarning murjaatlari')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MainSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecteds', to='service.surveyanswer')),
            ],
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='service.surveyquestion'),
        ),
    ]
