# Generated by Django 5.0 on 2024-06-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_surveyanswer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
