# Generated by Django 5.0 on 2024-06-10 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_faq_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='useropinion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
