# Generated by Django 5.0 on 2024-06-12 12:25

import custom.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_surveyquestion_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondSurveyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(validators=[custom.models.json_field_validate])),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('0', 'Variant 0'), ('1', 'Variant 1'), ('2', 'Variant 2'), ('3', 'Variant 3')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SecondSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('0', 'A’lo darajada'), ('1', 'Yaxshi darajada'), ('2', 'Qoniqarli darajada'), ('3', 'Qoniqarsiz darajada')], max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.secondsurveyservice')),
            ],
        ),
    ]
