# Generated by Django 5.0 on 2024-06-13 15:22

import custom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_centralapparatus_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.JSONField(default={'ru': 'ru'}, validators=[custom.models.json_field_validate]),
            preserve_default=False,
        ),
    ]
