# Generated by Django 5.0 on 2024-06-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_advert_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='text_footer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='text_header',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
