# Generated by Django 5.0 on 2024-06-03 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_documents', '0003_opensourcedocumentscategory_opensourcedocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='opensourcedocuments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opensourcedocuments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
