# Generated by Django 5.0 on 2024-06-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_documents', '0004_opensourcedocuments_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='text_footer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='text_header',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opensourcedocumentscategory',
            name='text_footer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opensourcedocumentscategory',
            name='text_header',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
